# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
